version: "3.8"
services:
  coturn:
    build: ./coturn
    restart: unless-stopped
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "9641:9641"
      - "10000-10005:10000-10005"
    links: 
      - mongo
    depends_on: 
      - mongo
  mongo:
    build: ./mongo
    ports: 
      - "27017:27017"
  prometheus:
    build: ./prometheus
    ports: 
      - "9090:9090"
    links:
      - coturn
  grafana:
    image: grafana/grafana 
    ports: 
      - "3000:3000"
    links: 
      - prometheus